### ISSUE TITLE
Typo, maybe?

### ISSUE THREAD

**Issue by meztez** [dgkf/options#5] opened 2023-11-28 18:57 UTC
https://github.com/dgkf/options/blob/7a86cbeba643024acf198b7618477da3499b14bc/R/options_roxygen.R#L42

Sys.getenv duplicated, maybe Sys.setenv?

**Comment by dgkf** [comment] 2023-11-28 18:59
Thanks for reporting! You're absolutely right, one of these looks like it was intended to be `Sys.setenv`.

**Comment by dgkf** [comment] 2023-11-28 20:09
Thanks again @meztez - Closing this issue now the the PR is merged.

**Closed as completed by dgkf** 2023-11-28 20:09 UTC
